"use client";

import { ChevronRight } from "lucide-react";
import Link from "next/link";

const Page = () => {
  return (
    <div className="space-y-8 py-16">
      <div className="container max-w-6xl mx-auto px-4 space-y-12">
        <section className="space-y-6">
          <h2 className="text-3xl font-bold tracking-tight">API Reference</h2>
          <p className="text-lg text-muted-foreground my-4">
            Here you'll find detailed specifications for each API endpoint.
          </p>
        </section>
        <section className="space-y-6">
          <div>
            <h3 className="text-2xl font-semibold tracking-tight">
              Get Images
            </h3>
            <p className="text-muted-foreground mt-6">
              Retrieve a list of all images generated by the user.
            </p>
            <Link href="/api-docs/api-reference/get-images">
              <div className="flex items-center mt-4 justify-between px-6 py-4 rounded-lg text-muted-foreground border border-border hover:border-zinc-700 hover:text-zinc-700 transition-colors duration-200">
                <span className="text-lg font-medium">Get Images</span>
                <ChevronRight className="h-5 w-5 text-zinc-400 group-hover:translate-x-1 transition-transform" />
              </div>
            </Link>
          </div>
          <div>
            <h3 className="text-2xl font-semibold tracking-tight">
              Image Generation
            </h3>
            <p className="text-muted-foreground mt-6">
              Generate images based on text prompts.
            </p>
            <Link href="/api-docs/api-reference/standard-image-generation">
              <div className="flex items-center mt-4 justify-between px-6 py-4 rounded-lg text-muted-foreground border border-border hover:border-zinc-700 hover:text-zinc-700 transition-colors duration-200">
                <span className="text-lg font-medium">
                  Create Standard Image
                </span>
                <ChevronRight className="h-5 w-5 text-zinc-400 group-hover:translate-x-1 transition-transform" />
              </div>
            </Link>
            <Link href="/api-docs/api-reference/premium-image-generation">
              <div className="flex items-center mt-4 justify-between px-6 py-4 rounded-lg text-muted-foreground border border-border hover:border-zinc-700 hover:text-zinc-700 transition-colors duration-200">
                <span className="text-lg font-medium">
                  Create Premium Image
                </span>
                <ChevronRight className="h-5 w-5 text-zinc-400 group-hover:translate-x-1 transition-transform" />
              </div>
            </Link>
          </div>
          <div>
            <h3 className="text-2xl font-semibold tracking-tight">
              Remove Background
            </h3>
            <p className="text-muted-foreground mt-6">
              Remove the background from an image.
            </p>
            <Link href="/api-docs/api-reference/remove-background">
              <div className="flex items-center mt-4 justify-between px-6 py-4 rounded-lg text-muted-foreground border border-border hover:border-zinc-700 hover:text-zinc-700 transition-colors duration-200">
                <span className="text-lg font-medium">Remove Background</span>
                <ChevronRight className="h-5 w-5 text-zinc-400 group-hover:translate-x-1 transition-transform" />
              </div>
            </Link>
          </div>
          <div>
            <h3 className="text-2xl font-semibold tracking-tight">
              Image Upscaling
            </h3>
            <p className="text-muted-foreground mt-6">
              Upscale an image to a higher resolution.
            </p>
            <Link href="/api-docs/api-reference/upscale-image">
              <div className="flex items-center mt-4 justify-between px-6 py-4 rounded-lg text-muted-foreground border border-border hover:border-zinc-700 hover:text-zinc-700 transition-colors duration-200">
                <span className="text-lg font-medium">Upscale Image</span>
                <ChevronRight className="h-5 w-5 text-zinc-400 group-hover:translate-x-1 transition-transform" />
              </div>
            </Link>
          </div>
        </section>
      </div>
    </div>
  );
};

export default Page;
