"use client";

const Page = () => {
  return (
    <div className="min-h-screen bg-background w-screen">
      <div className="pt-24 pb-12 text-center">
        <h1 className="text-4xl font-semibold tracking-[-0.022em] mb-4">
          Terms of Service
        </h1>
        <p className="text-xl font-light text-muted-foreground">
          Soreal – a service of Soreal AI, LLC
        </p>
        <p className="text-sm font-light text-muted-foreground mt-2">
          Last updated & Effective date: 19 May 2025
        </p>
      </div>

      <div className="max-w-[900px] mx-auto px-6 pb-24">
        <div className="prose prose-gray max-w-none">
          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              Introduction & Acceptance
            </h2>
            <p className="text-gray-700 font-light leading-relaxed">
              These Terms of Service ("Terms") constitute a binding legal
              agreement between Soreal AI, LLC ("Soreal," "we," "our," or "us")
              and the individual or entity accessing or using Soreal ("User,"
              "you," or "your"). Soreal is an artificial-intelligence platform
              that enables the creation of photorealistic digital images and
              related content (collectively, "Assets").
            </p>
            <p className="text-gray-700 font-light leading-relaxed mt-4">
              By (i) visiting http://soreal.app (the "Site"), (ii) creating an
              account, (iii) accessing the Soreal application-programming
              interface ("API"), or (iv) otherwise using any software, mobile or
              desktop application, feature, or service we make available
              (together with the Site, the "Service"), you:
            </p>
            <ol className="list-decimal pl-6 mt-4 space-y-2 text-gray-700 font-light">
              <li>
                acknowledge that you have read and understood these Terms and
                our{" "}
                <a
                  href="/privacy-policy"
                  className="text-[#2fceb9] hover:underline"
                >
                  Privacy Policy
                </a>{" "}
                (available at http://soreal.app/privacy);
              </li>
              <li>agree to be bound by them; and</li>
              <li>
                represent that you are at least eighteen (18) years old, or the
                age of majority in your jurisdiction, whichever is higher, and
                have the legal capacity to enter into contracts.
              </li>
            </ol>
            <p className="text-gray-700 font-light leading-relaxed mt-4">
              If you do not agree to all provisions of these Terms, do not
              access or use the Service.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              2. Definitions
            </h2>
            <div className="overflow-x-auto">
              <table className="min-w-full border-collapse">
                <thead>
                  <tr className="border-b border-gray-200">
                    <th className="py-3 px-4 text-left font-medium text-gray-900 w-1/4">
                      Term
                    </th>
                    <th className="py-3 px-4 text-left font-medium text-gray-900">
                      Meaning
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 align-top font-medium">
                      Asset(s)
                    </td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      All images, derivatives, metadata, or other outputs
                      generated by the Service in response to a prompt or
                      upload.
                    </td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 align-top font-medium">Prompt</td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Any text, image, or other data you submit to the Service
                      for the purpose of generating an Asset.
                    </td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 align-top font-medium">
                      Free Tier
                    </td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      No-cost plan with limited functionality and non-commercial
                      usage rights.
                    </td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 align-top font-medium">
                      Paid Tier
                    </td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Fee-based subscription plan (monthly or annual) that
                      includes commercial rights and expanded features.
                    </td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 align-top font-medium">
                      User Content
                    </td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      All Prompts, uploads, profile details, feedback, or other
                      material provided by you.
                    </td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 align-top font-medium">Credits</td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Units that measure and debit resource consumption (e.g.,
                      number of image generations) under the Paid Tier or API
                      plan.
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              3. The Service
            </h2>
            <ol className="list-decimal pl-6 space-y-4 text-gray-700 font-light">
              <li>
                <span className="font-medium">Functionality.</span> Soreal uses
                proprietary and third-party machine-learning models to transform
                Prompts into Assets with photorealistic qualities. You may
                interact with the models via a browser-based interface or via
                the API.
              </li>
              <li>
                <span className="font-medium">Evolving features.</span> AI
                technology changes rapidly. We may add, modify, or discontinue
                models or features at any time. Material changes will be
                announced via in-app notice or email.
              </li>
              <li>
                <span className="font-medium">Third-party integration.</span>{" "}
                The Service relies on cloud providers (e.g., Supabase LLC for
                storage and Postgres database hosting; CDN vendors; logging and
                analytics processors). Your data may transit or reside on their
                infrastructure.
              </li>
            </ol>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              4. Account Registration & Security
            </h2>
            <ul className="list-disc pl-6 space-y-4 text-gray-700 font-light">
              <li>
                <span className="font-medium">Accuracy.</span> You must provide
                true, current, and complete information during sign-up and keep
                it updated.
              </li>
              <li>
                <span className="font-medium">One account per user.</span> Each
                natural person or legal entity may register a single primary
                account.
              </li>
              <li>
                <span className="font-medium">Credentials responsibility.</span>{" "}
                You are fully responsible for any activity under your
                credentials. Notify us immediately at support@soreal.app if you
                suspect unauthorized use.
              </li>
              <li>
                <span className="font-medium">Account sharing.</span> Selling,
                renting, or sharing access keys, passwords, or API tokens is
                prohibited. We reserve the right to suspend or terminate
                accounts that violate this rule.
              </li>
            </ul>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              5. Plan Types, Fees, Billing, & Taxes
            </h2>

            <h3 className="text-xl font-medium mb-4">
              5.1 Current plan structure
            </h3>
            <div className="overflow-x-auto mb-8">
              <table className="min-w-full border-collapse">
                <thead>
                  <tr className="border-b border-gray-200">
                    <th className="py-3 px-4 text-left font-medium text-gray-900">
                      Feature
                    </th>
                    <th className="py-3 px-4 text-left font-medium text-gray-900">
                      Free Tier
                    </th>
                    <th className="py-3 px-4 text-left font-medium text-gray-900">
                      Paid Tier
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 font-medium">Monthly price</td>
                    <td className="py-3 px-4 text-gray-700 font-light">$0</td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      See current price list
                    </td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 font-medium">Commercial rights</td>
                    <td className="py-3 px-4 text-gray-700 font-light">No</td>
                    <td className="py-3 px-4 text-gray-700 font-light">Yes</td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 font-medium">Asset ownership</td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Soreal retains IP (personal-use licence to User)
                    </td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Copyright assigned to User
                    </td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 font-medium">
                      Model-training opt-in
                    </td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Mandatory to Soreal
                    </td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Voluntary (default opt-out)
                    </td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 font-medium">API access</td>
                    <td className="py-3 px-4 text-gray-700 font-light">None</td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Included (rate-limited)
                    </td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 font-medium">Gallery listing</td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Automatic
                    </td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Opt-in
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p className="text-gray-700 font-light leading-relaxed">
              Prices, quotas, and benefits may be revised upon at least thirty
              (30) days' notice.
            </p>

            <h3 className="text-xl font-medium mt-8 mb-4">
              5.2 Subscription mechanics
            </h3>
            <ul className="list-disc pl-6 space-y-4 text-gray-700 font-light">
              <li>
                <span className="font-medium">Billing cycle.</span> Fees are
                charged in advance on a monthly or annual basis (as selected).
              </li>
              <li>
                <span className="font-medium">Auto-renewal.</span> Subscriptions
                auto-renew unless cancelled before the end of the current
                period.
              </li>
              <li>
                <span className="font-medium">Refund policy.</span> Fees are
                non-refundable, except where required by applicable
                consumer-protection law.
              </li>
              <li>
                <span className="font-medium">Taxes.</span> Prices are exclusive
                of federal, state, local, VAT/GST, or other taxes. You are
                responsible for all applicable taxes, duties, and similar
                assessments. We may charge and remit taxes where legally
                required.
              </li>
            </ul>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              6. Asset Ownership, Licences & User Content
            </h2>

            <h3 className="text-xl font-medium mb-4">6.1 Free Tier</h3>
            <ul className="list-disc pl-6 space-y-4 text-gray-700 font-light">
              <li>
                <span className="font-medium">Licence to you.</span> Soreal
                grants you a non-exclusive, non-transferable, revocable licence
                to use Free Tier Assets for personal, non-commercial purposes.
              </li>
              <li>
                <span className="font-medium">Ownership.</span> All
                intellectual-property rights in Free Tier Assets remain with
                Soreal.
              </li>
              <li>
                <span className="font-medium">Training & gallery.</span> By
                using the Free Tier, you consent to Soreal (i) displaying your
                Assets publicly and (ii) using them and corresponding Prompts to
                train and improve Soreal models.
              </li>
            </ul>

            <h3 className="text-xl font-medium mt-8 mb-4">6.2 Paid Tier</h3>
            <ul className="list-disc pl-6 space-y-4 text-gray-700 font-light">
              <li>
                <span className="font-medium">Assignment.</span> Upon successful
                generation and payment, Soreal irrevocably assigns to you all
                worldwide copyrights in each Paid Tier Asset.
              </li>
              <li>
                <span className="font-medium">Restrictions.</span> You may not
                use any Asset (Free or Paid) to train, fine-tune, or otherwise
                develop any AI model or dataset, whether commercial or
                open-source.
              </li>
              <li>
                <span className="font-medium">Opt-in training.</span> You may
                voluntarily grant Soreal permission to use specific Paid Tier
                Assets for model training by enabling the "opt-in" toggle in
                account settings.
              </li>
            </ul>

            <h3 className="text-xl font-medium mt-8 mb-4">
              6.3 User Content licence to Processfy
            </h3>
            <p className="text-gray-700 font-light leading-relaxed">
              By submitting Prompts, uploads, or feedback, you grant Soreal a
              perpetual, worldwide, royalty-free licence to store, process,
              reproduce, adapt, translate, and otherwise use such content solely
              for:
            </p>
            <ol className="list-decimal pl-6 mt-4 space-y-2 text-gray-700 font-light">
              <li>providing, maintaining, and improving the Service;</li>
              <li>enforcing these Terms and complying with law;</li>
              <li>
                displaying content in any Soreal public gallery if you have
                opted-in (Paid Tier) or are a Free Tier user.
              </li>
            </ol>
            <p className="text-gray-700 font-light leading-relaxed mt-4">
              We will not use your uploaded reference images for model training
              without your explicit opt-in consent.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              7. Data Handling & Storage
            </h2>
            <ol className="list-decimal pl-6 space-y-4 text-gray-700 font-light">
              <li>
                <span className="font-medium">Infrastructure.</span> Assets and
                User Content are stored in Supabase-managed buckets located in
                data centres in the United States. Logs and analytics may be
                processed by US- or EU-based providers.
              </li>
              <li>
                <span className="font-medium">Cross-border transfers.</span> By
                using the Service, you consent to international data transfer,
                processing, and storage as described in our Privacy Policy.
              </li>
              <li>
                <span className="font-medium">Security.</span> We employ
                industry-standard technical and organizational measures, but no
                system is perfectly secure. You accept inherent risks.
              </li>
            </ol>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              8. API Terms
            </h2>
            <ol className="list-decimal pl-6 space-y-4 text-gray-700 font-light">
              <li>
                <span className="font-medium">Keys & secrecy.</span> Keep API
                keys confidential. Keys are unique to your account and
                consumption is billed to you.
              </li>
              <li>
                <span className="font-medium">Rate limits & fair use.</span>{" "}
                Current default limit is 100 requests per minute and 60 seconds
                maximum execution per request. We may adjust limits with notice.
              </li>
              <li>
                <span className="font-medium">Credit debit.</span> Each
                generation, upscale, or background-removal action debits the
                number of credits shown in the API documentation. Credits expire
                with the underlying subscription term.
              </li>
              <li>
                <span className="font-medium">Monitoring.</span> We may monitor
                API traffic for security, rate-limit enforcement, and abuse
                detection.
              </li>
            </ol>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              9. Acceptable-Use Policy (AUP)
            </h2>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              You agree not to do any of the following:
            </p>
            <ul className="list-disc pl-6 space-y-4 text-gray-700 font-light">
              <li>
                <span className="font-medium">Illegal content</span> – Generate
                or upload content that violates any law or depicts exploitative
                or harmful material.
              </li>
              <li>
                <span className="font-medium">Harassment & hate</span> – Produce
                content that is harassing, hateful, or otherwise discriminatory.
              </li>
              <li>
                <span className="font-medium">Child endangerment</span> – Any
                depiction or sexualization of minors is strictly forbidden.
              </li>
              <li>
                <span className="font-medium">Misinformation</span> – Generate
                verifiably false content with intent to deceive or harm.
              </li>
              <li>
                <span className="font-medium">Privacy violations</span> – Upload
                personal data without consent or create deepfakes of real
                individuals without permission.
              </li>
              <li>
                <span className="font-medium">Security breaches</span> – Probe,
                scan, or test the vulnerability of the Service, circumvent rate
                limits, or gain unauthorized access.
              </li>
              <li>
                <span className="font-medium">Automated abuse</span> – Use bots
                or scripts outside the official API.
              </li>
              <li>
                <span className="font-medium">Model extraction</span> – Attempt
                to reverse-engineer or replicate Soreal models.
              </li>
            </ul>
            <p className="text-gray-700 font-light leading-relaxed mt-4">
              Violations may result in suspension, account termination, and
              legal action.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              10. Public Gallery & Community Assets
            </h2>
            <ul className="list-disc pl-6 space-y-4 text-gray-700 font-light">
              <li>
                <span className="font-medium">Default inclusion.</span> Free
                Tier Assets may appear in a browsable gallery under a Creative
                Commons Attribution-NonCommercial-NoDerivatives licence unless
                prohibited by law.
              </li>
              <li>
                <span className="font-medium">Paid Tier opt-in.</span> Paid
                Users may elect to showcase certain Assets publicly.
              </li>
              <li>
                <span className="font-medium">Takedown.</span> You may request
                removal of publicly displayed Assets you own by emailing
                legal@soreal.app; we will remove them within a commercially
                reasonable time.
              </li>
            </ul>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              11. Suspension, Termination & Survival
            </h2>
            <ul className="list-disc pl-6 space-y-4 text-gray-700 font-light">
              <li>
                <span className="font-medium">User cancellation.</span> Cancel
                via account settings. Benefits remain active until the end of
                the paid period; no prorated refunds.
              </li>
              <li>
                <span className="font-medium">Our termination rights.</span> We
                may suspend or terminate accounts that violate these Terms or
                create legal exposure.
              </li>
              <li>
                <span className="font-medium">Effect of termination.</span> All
                licences granted under these Terms terminate; Paid Tier
                ownership of existing Assets survives. Sections on Disclaimers,
                Limitation of Liability, Indemnification, Governing Law, and
                Dispute Resolution survive termination.
              </li>
            </ul>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              12. Disclaimers
            </h2>
            <p className="text-gray-700 font-light leading-relaxed uppercase">
              THE SERVICE, ASSETS, AND ALL RELATED MATERIALS ARE PROVIDED "AS
              IS," "AS AVAILABLE," WITHOUT WARRANTY OF ANY KIND—EXPRESS,
              IMPLIED, OR STATUTORY—including warranties of merchantability,
              fitness for a particular purpose, non-infringement, uninterrupted
              availability, or error-free operation.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              13. Limitation of Liability
            </h2>
            <p className="text-gray-700 font-light leading-relaxed uppercase">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, SOREAL AI, LLC AND ITS
              OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR
              ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR
              EXEMPLARY DAMAGES. OUR TOTAL AGGREGATE LIABILITY IN CONNECTION
              WITH THE SERVICE SHALL NOT EXCEED US $50 or the total amount you
              paid to Soreal during the six (6) months preceding the event
              giving rise to liability, whichever is greater.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              14. Indemnification
            </h2>
            <p className="text-gray-700 font-light leading-relaxed">
              You will defend, indemnify, and hold harmless Soreal and its
              affiliates from any claim, demand, loss, or damage (including
              reasonable attorneys' fees) arising out of your (i) violation of
              these Terms, (ii) User Content, or (iii) use of Assets in breach
              of third-party rights.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              15. Governing Law & Dispute Resolution
            </h2>
            <ol className="list-decimal pl-6 space-y-4 text-gray-700 font-light">
              <li>
                <span className="font-medium">Choice of law.</span> These Terms
                are governed by the laws of the State of Delaware, without
                regard to conflict-of-law principles.
              </li>
              <li>
                <span className="font-medium">Informal resolution.</span> Before
                filing a claim, you must email legal@soreal.app with a concise
                "Notice of Dispute," and the parties will attempt good-faith
                resolution within thirty (30) days.
              </li>
              <li>
                <span className="font-medium">Arbitration.</span> Unresolved
                disputes shall be finally settled by binding arbitration
                administered by JAMS under its Streamlined Arbitration Rules.
                Seat of arbitration: Orange County, California, USA.
              </li>
              <li>
                <span className="font-medium">Class-action waiver.</span> All
                claims must be brought in an individual capacity; class actions
                and class arbitrations are waived.
              </li>
              <li>
                <span className="font-medium">Opt-out.</span> You may opt out of
                arbitration by sending a signed opt-out notice to
                legal@soreal.app within thirty (30) days of your first
                acceptance of these Terms.
              </li>
            </ol>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              16. Modifications to Terms
            </h2>
            <p className="text-gray-700 font-light leading-relaxed">
              Soreal may revise these Terms from time to time. Material
              revisions will be communicated at least fifteen (15) days before
              they take effect via email or in-Service notice. Continued use
              after the effective date constitutes acceptance of the revised
              Terms.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              17. Miscellaneous
            </h2>
            <ul className="list-disc pl-6 space-y-4 text-gray-700 font-light">
              <li>
                <span className="font-medium">Entire agreement.</span> These
                Terms, plus any policies linked herein, constitute the entire
                agreement between you and Soreal regarding the Service.
              </li>
              <li>
                <span className="font-medium">Severability.</span> If any
                provision is held to be unenforceable, the remaining provisions
                remain in full force.
              </li>
              <li>
                <span className="font-medium">Assignment.</span> You may not
                assign your rights or obligations under these Terms without our
                prior written consent; we may assign freely.
              </li>
              <li>
                <span className="font-medium">No waiver.</span> Our failure to
                enforce any right is not a waiver of future enforcement.
              </li>
              <li>
                <span className="font-medium">Force majeure.</span> We are not
                liable for delays or failures caused by events beyond our
                reasonable control (e.g., natural disasters, internet outages,
                governmental acts).
              </li>
            </ul>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              18. Contact Information
            </h2>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              For technical support, billing questions, or legal notices:
            </p>
            <div className="bg-gray-50 p-6 rounded-lg">
              <p className="font-medium mb-2">Soreal AI, LLC</p>
              <p className="text-gray-700 font-light">8 The Green #18947</p>
              <p className="text-gray-700 font-light mb-4">
                Dover, DE 19901 USA
              </p>

              <p className="text-gray-700 font-light">
                Email:{" "}
                <a
                  href="mailto:support@soreal.app"
                  className="text-[#2fceb9] hover:underline"
                >
                  support@soreal.app
                </a>{" "}
                | Legal:{" "}
                <a
                  href="mailto:legal@soreal.app"
                  className="text-[#2fceb9] hover:underline"
                >
                  legal@soreal.app
                </a>
              </p>
            </div>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <p className="text-sm text-gray-500 font-light text-center">
            Last revised: 19 May 2025
          </p>
        </div>
      </div>
    </div>
  );
};

export default Page;
