"use client";

const Page = () => {
  return (
    <div className="min-h-screen bg-background w-screen">
      <div className="pt-24 pb-12 text-center">
        <h1 className="text-4xl font-semibold tracking-[-0.022em] mb-4">
          Terms of Service
        </h1>
        <p className="text-xl font-light text-muted-foreground">
          Soreal – a service of Soreal AI, LLC
        </p>
        <p className="text-sm font-light text-muted-foreground mt-2">
          Last updated & Effective date: 19 May 2025
        </p>
      </div>

      <div className="max-w-[900px] mx-auto px-6 pb-24">
        <div className="prose prose-gray max-w-none">
          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              1. Introduction & Acceptance
            </h2>
            <p className="text-gray-700 font-light leading-relaxed">
              Soreal AI, LLC ("Soreal," "we," "our," or "us") operates an artificial-intelligence platform that enables the creation of photorealistic digital images and related content (collectively, "Assets"). These Terms of Service ("Terms") constitute a binding legal agreement between Soreal and you, the individual or entity accessing or using the Soreal service ("User," "you," or "your"). These Terms govern your access to and use of Soreal's services, including our website at soreal.app (the "Site"), our application-programming interface (the "API"), and any other software, mobile or desktop application, feature, or service we make available (together with the Site, the "Service").
            </p>
            <p className="text-gray-700 font-light leading-relaxed mt-4">
              By performing any of the following actions, you indicate your acceptance of and agreement to these Terms and our Privacy Policy:
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2 text-gray-700 font-light">
              <li>(i) visiting soreal.app or otherwise accessing the Site;</li>
              <li>(ii) creating an account on the Service;</li>
              <li>(iii) accessing or using the Soreal API; or</li>
              <li>(iv) using any other feature or part of the Service.</li>
            </ul>
            <p className="text-gray-700 font-light leading-relaxed mt-4">
              By accepting these Terms, you further represent that you are at least eighteen (18) years old (or the age of majority in your jurisdiction, if higher) and have the legal capacity to enter into contracts. If you do not agree to all provisions of these Terms, you must not access or use the Service.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              2. Definitions
            </h2>
            <div className="overflow-x-auto">
              <table className="min-w-full border-collapse">
                <thead>
                  <tr className="border-b border-gray-200">
                    <th className="py-3 px-4 text-left font-medium text-gray-900 w-1/4">
                      Term
                    </th>
                    <th className="py-3 px-4 text-left font-medium text-gray-900">
                      Meaning
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 align-top font-medium">
                      Asset(s)
                    </td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      All images, derivatives, metadata, or other outputs generated by the Service in response to a Prompt or upload.
                    </td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 align-top font-medium">Prompt</td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Any text, image, or other data you submit to the Service for the purpose of generating an Asset.
                    </td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 align-top font-medium">
                      Free Tier
                    </td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Our no-cost plan with limited functionality and non-commercial usage rights.
                    </td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 align-top font-medium">
                      Paid Tier
                    </td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      A fee-based subscription plan (monthly or annual) that includes commercial usage rights and expanded features.
                    </td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 align-top font-medium">
                      User Content
                    </td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      All Prompts, uploads, profile details, feedback, or other material provided by you to the Service.
                    </td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 align-top font-medium">Credits</td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Units that measure and debit resource consumption on the Service (e.g. the number of image generations), used under a Paid Tier subscription or API plan.
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              3. The Service
            </h2>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Functionality.</span> Soreal uses proprietary and third-party machine-learning models to transform Prompts into photorealistic Assets. You may interact with these models via a browser-based interface or through our API, to generate, modify, or enhance images as supported by the Service.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Evolving Features.</span> Artificial intelligence technology evolves rapidly, and features of the Service may change over time. We reserve the right to add, modify, or discontinue models or features at any time. If we make material changes to the Service or its functionality, we will provide notice (for example, via an in-app announcement or email) prior to or upon implementing the changes.
            </p>
            <p className="text-gray-700 font-light leading-relaxed">
              <span className="font-medium">Third-Party Integration.</span> The Service relies on third-party infrastructure and integrations to function effectively. For example, we utilize cloud service providers (such as Supabase LLC for storage and Postgres database hosting), content delivery networks, and logging and analytics services. You acknowledge that your data and User Content may be transmitted through or stored on these third-party systems as necessary for the normal operation of the Service.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              4. Account Registration & Security
            </h2>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Accuracy of Information.</span> When creating an account, you agree to provide true, current, and complete information as requested, and to keep your registration details up to date. You must not misrepresent your identity or affiliations.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">One Account Per User.</span> Each natural person or legal entity is limited to a single primary Soreal account. You may not create multiple accounts for the same person or entity without our express permission.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Credentials Responsibility.</span> You are responsible for maintaining the confidentiality and security of your account credentials (username, password, API keys, etc.). You are fully liable for all activities that occur under your account. If you suspect any unauthorized use of your account or a security breach, you must notify us immediately at support@soreal.app.
            </p>
            <p className="text-gray-700 font-light leading-relaxed">
              <span className="font-medium">Account Sharing Prohibited.</span> You may not sell, rent, share, or transfer your account or access credentials (including API tokens) to any other person or entity. Soreal reserves the right to suspend or terminate any account that we believe is being used in violation of this rule.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              5. Plan Types, Fees, Billing, & Taxes
            </h2>

            <h3 className="text-xl font-medium mb-4">
              5.1 Current Plan Structure
            </h3>
            <div className="overflow-x-auto mb-8">
              <table className="min-w-full border-collapse">
                <thead>
                  <tr className="border-b border-gray-200">
                    <th className="py-3 px-4 text-left font-medium text-gray-900">
                      Feature
                    </th>
                    <th className="py-3 px-4 text-left font-medium text-gray-900">
                      Free Tier (Personal Use)
                    </th>
                    <th className="py-3 px-4 text-left font-medium text-gray-900">
                      Paid Tier (Subscription)
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 font-medium">Monthly price</td>
                    <td className="py-3 px-4 text-gray-700 font-light">$0 (no cost)</td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      See current price list (monthly or annual options)
                    </td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 font-medium">Commercial usage rights</td>
                    <td className="py-3 px-4 text-gray-700 font-light">No (personal/non-commercial use only)</td>
                    <td className="py-3 px-4 text-gray-700 font-light">Yes (commercial use permitted)</td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 font-medium">Asset ownership</td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Soreal retains IP (User gets personal-use license)
                    </td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Copyright in Assets assigned to User upon creation
                    </td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 font-medium">
                      Model-training opt-in
                    </td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Mandatory contribution to Soreal's training dataset
                    </td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Voluntary (opt-out by default; user can choose to opt-in)
                    </td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 font-medium">API access</td>
                    <td className="py-3 px-4 text-gray-700 font-light">Not included</td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Included (with rate limits as per plan)
                    </td>
                  </tr>
                  <tr className="border-b border-gray-200">
                    <td className="py-3 px-4 font-medium">Public gallery listing</td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Automatic (Assets may be publicly visible)
                    </td>
                    <td className="py-3 px-4 text-gray-700 font-light">
                      Opt-in (User can choose to showcase Assets)
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p className="text-gray-700 font-light leading-relaxed mb-6">
              <strong>Note:</strong> Prices, usage quotas, and benefits of each plan are subject to change. If we make any material changes to our plans or pricing, we will provide at least thirty (30) days' notice to affected users (for example, via email or an in-Service notification).
            </p>

            <h3 className="text-xl font-medium mt-8 mb-4">
              5.2 Subscription Mechanics
            </h3>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Billing Cycle.</span> All subscription fees for the Paid Tier are charged in advance on a recurring basis (either monthly or annually, depending on the plan you select). Your billing cycle begins on the date you subscribe and renews on the same date of the next period unless changed.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Auto-Renewal.</span> Paid Tier subscriptions will automatically renew at the end of each billing period unless you cancel your subscription before the end of the current paid term. By subscribing, you authorize Soreal to charge the then-applicable subscription fees to your payment method on file at each renewal.
            </p>
            
            <div className="bg-blue-50 border-l-4 border-blue-400 p-4 mb-4">
              <h4 className="font-medium text-blue-900 mb-2">Refund Policy</h4>
              <ul className="list-disc pl-5 space-y-1 text-blue-800 font-light">
                <li>Subscriptions are eligible for refunds upon request.</li>
                <li>Refunds will be prorated based on the number of credits used.</li>
                <li>Top-up credits are non-refundable once delivered.</li>
                <li>Annual plans can be refunded within 30 days of purchase.</li>
              </ul>
            </div>

            <p className="text-gray-700 font-light leading-relaxed">
              <span className="font-medium">Taxes.</span> All fees and prices are exclusive of any taxes, levies, or duties imposed by taxing authorities. You are responsible for paying any applicable taxes (e.g., sales tax, value-added tax (VAT), Goods and Services Tax (GST), etc.) that may apply to your purchase or use of the Service. If Soreal is legally obligated to collect taxes, we will add the appropriate amount to your billing total and remit those taxes to the relevant authorities as required by law.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              6. Asset Ownership, Licenses & User Content
            </h2>

            <h3 className="text-xl font-medium mb-4">6.1 Free Tier</h3>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Personal Use License to User.</span> For Assets you generate while using the Free Tier, Soreal grants you a limited, personal, non-exclusive, non-transferable, revocable license to use, display, and share those Assets for your own personal, non-commercial purposes. This means you may not sell, license, or otherwise exploit Free Tier Assets for any commercial gain.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Soreal Retains Ownership.</span> All intellectual property rights in Free Tier Assets remain owned by Soreal. Except for the personal-use license granted above, you obtain no ownership rights or title in Free Tier outputs. Soreal may reuse or redistribute Free Tier Assets in our discretion (for example, for product improvement or showcasing user creations), as described below.
            </p>
            <p className="text-gray-700 font-light leading-relaxed">
              <span className="font-medium">Training and Public Gallery.</span> By using the Free Tier, you acknowledge and agree that: (i) Soreal may display or publish any Assets you create on the Free Tier in a public gallery or portfolio for others to view, and (ii) Soreal may use Free Tier Assets and the associated Prompts to further train, develop, and improve Soreal's algorithms and models. If you prefer to keep your creations private and opt out of contributing to model training, please upgrade to a Paid Tier plan where these are optional.
            </p>

            <h3 className="text-xl font-medium mt-8 mb-4">6.2 Paid Tier</h3>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Assignment of Copyright to User.</span> Upon the successful generation of an Asset under the Paid Tier (and subject to your account being in good standing and payment of all fees), Soreal irrevocably assigns to you all worldwide copyrights and intellectual property rights in that Asset. In other words, for Paid Tier outputs, you become the owner of the Asset's intellectual property once it is created, and you may use the Asset commercially or non-commercially at your discretion, subject to these Terms.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Retention of Rights by Soreal.</span> Notwithstanding the above assignment, you acknowledge that Soreal and its model licensors retain ownership of the underlying AI models and algorithms. You do not acquire any rights to the Soreal software or models themselves. This section only transfers rights in the specific image output (Asset) that has been generated for you.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Use Restrictions (Free & Paid).</span> Whether you are on the Free or Paid Tier, you agree that you will not use any Asset generated by the Service to train, fine-tune, or otherwise develop any artificial intelligence model or dataset, whether for commercial purposes or open-source/non-commercial purposes. In addition, you may not use any Asset in a manner that violates the Acceptable Use Policy (see Section 9) or any applicable law.
            </p>
            <p className="text-gray-700 font-light leading-relaxed">
              <span className="font-medium">Model Training Opt-In (Paid Tier).</span> By default, Paid Tier users are opted in to allow their generated Assets and Prompts to be used for model training and public display. This helps improve Soreal's models and features over time. You may opt out at any time through your account settings. Once opted out, any new Assets and Prompts you generate will be excluded from future training or public use. However, any content used for training prior to opting out will remain part of the model's training history and cannot be removed retroactively.
            </p>

            <h3 className="text-xl font-medium mt-8 mb-4">
              6.3 User Content License to Soreal
            </h3>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              By submitting or uploading any User Content to the Service (including without limitation your Prompts, reference images, feedback, or profile information), you grant Soreal a perpetual, worldwide, royalty-free, irrevocable license to store, process, reproduce, adapt, modify, translate, and otherwise use that User Content solely for the following purposes:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700 font-light mb-4">
              <li><span className="font-medium">Service Provision and Improvement:</span> We may use your Prompts and uploads as necessary to operate the Service and to maintain and improve the performance of our algorithms.</li>
              <li><span className="font-medium">Enforcement of Terms & Legal Compliance:</span> We may use or preserve your User Content to investigate and enforce compliance with these Terms and applicable law.</li>
              <li><span className="font-medium">Public Gallery (Optional):</span> If you are on the Free Tier or if you are a Paid Tier user who has explicitly opted in to the public gallery, we may display certain Assets you create in a publicly accessible gallery or community feed.</li>
            </ul>
            <p className="text-gray-700 font-light leading-relaxed">
              Importantly, Soreal will NOT use any of your uploaded reference images for model training unless you have given explicit opt-in consent. Outside of an opt-in scenario, any private images or User Content you upload are used only to generate the outputs you requested and for the operational purposes listed above, not to add to our training datasets.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              7. Data Handling & Storage
            </h2>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Infrastructure.</span> You acknowledge that Assets and User Content you generate or provide may be stored in third-party infrastructure used by Soreal. Specifically, Soreal uses Supabase (a cloud service provider) to store Assets and related data in managed object storage buckets and to host our Postgres databases. These servers are currently located in data centers within the United States. Additionally, logs and analytics data from your usage of the Service may be processed by third-party providers which could be based in the U.S. or the EU.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Cross-Border Data Transfers.</span> By using the Service, you consent to the transfer of your data (including personal data and User Content) across international borders as necessary for our operations. This may mean that your data is transferred to, stored in, or processed in a country different from your own. Soreal will handle all data in accordance with our Privacy Policy and will take appropriate measures to protect it, but we make no representations that the data laws of the hosting country provide the same level of protection as those in your home jurisdiction.
            </p>
            <p className="text-gray-700 font-light leading-relaxed">
              <span className="font-medium">Security.</span> We employ industry-standard technical and organizational measures to protect the security of your data and our systems. This includes encryption of data at rest and in transit where appropriate, access controls, and regular security assessments. However, no system is perfectly secure, and we cannot guarantee that unauthorized third parties will never be able to defeat our measures or misuse your data. You acknowledge that you provide your data at your own risk and accept the inherent risks of transmitting information over the internet. In the event of a data breach that affects your personal information, we will notify you as required by applicable law.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              8. API Terms
            </h2>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">API Keys & Secrecy.</span> If you are provided an API key or token to access the Soreal API, you must keep it confidential. Your API credentials are unique to your account and you are responsible for all usage of the Service that occurs under your key. Do not share, publish, or expose your API key to the public (for example, in client-side code or public repositories). If you believe your API key has been compromised, you must regenerate it or contact us immediately to avoid unauthorized use.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Rate Limits & Fair Use.</span> Use of the API is subject to rate limiting and fair use policies. The current default limit is 100 requests per minute and a maximum of 60 seconds of processing time per request. We may adjust these limits from time to time (and will notify you of significant changes). You agree not to intentionally circumvent or throttle these limits by any means. If your usage exceeds what we consider fair or reasonable for your plan (or appears to burden the Service), we may require you to upgrade plans or institute more restrictive limits on your access.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Credit Usage.</span> Certain API operations (such as generating an image, upscaling an image, or removing a background) will debit Credits from your account balance. The API documentation and/or your subscription plan will outline how many Credits each type of operation consumes. Ensure you have a sufficient Credits balance for the actions you wish to perform; if you run out of Credits, further API requests may be rejected or throttled until you purchase more or your subscription renews. Note: Credits are tied to your subscription period and may expire if not used within the period they were granted (for example, monthly Credits expire at the end of the month). Credits have no cash value and are not transferable.
            </p>
            <p className="text-gray-700 font-light leading-relaxed">
              <span className="font-medium">Monitoring and Compliance.</span> You acknowledge that Soreal may monitor API usage for security, debugging, improvement, and enforcement purposes. We may collect information such as request volume, error logs, and metadata about the requests (but not the content of your images, except as needed for processing). If we detect abuse of the API (for example, excessive usage beyond fair use, attempts to reverse-engineer the API or Service, or any violation of these Terms), we may suspend or terminate your API access. We also reserve the right to disable or modify any API functionality to protect the Service or comply with legal requirements.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              9. Acceptable Use Policy (AUP)
            </h2>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              When using Soreal, you agree that you will NOT generate, upload, share, or use content that falls into any of the following categories (or engage in any related conduct):
            </p>
            <ul className="list-disc pl-6 space-y-4 text-gray-700 font-light">
              <li>
                <span className="font-medium">Illegal or Criminal Activity:</span> Do not use the Service for any unlawful purposes. This includes creating forgeries or fraudulent content of any kind. For example, you may not use Soreal to generate forged identification documents, licenses, passports, counterfeit currency, or any image intended to facilitate fraud, impersonation (identity theft), or other crimes. You also may not use the Service to create or disseminate content that violates export controls, trade sanctions, or any applicable laws or regulations.
              </li>
              <li>
                <span className="font-medium">Harassment & Hate:</span> Do not use Soreal to create content that is intended to harass, bully, threaten, or incite violence against an individual or group. This includes content that is hateful, derogatory, or discriminatory on the basis of race, ethnicity, national origin, religion, sex, gender, sexual orientation, disability, or any other characteristic that is protected by law.
              </li>
              <li>
                <span className="font-medium">Child Endangerment:</span> Any content that exploits or endangers minors is strictly forbidden. You must not generate or share images depicting sexual content involving minors, or any situation that promotes the abuse, harm, or exploitation of children. Soreal has zero tolerance for content that sexualizes minors or suggests any form of child abuse.
              </li>
              <li>
                <span className="font-medium">Misinformation or Deception:</span> Do not use the Service to generate content that you know is false or misleading with the intent to deceive, defraud, or cause harm. This includes creating deepfakes or otherwise realistic but false images purporting to show events or individuals that did not exist or occur, when done in a harmful or malicious manner. Content that could mislead others in matters of public interest (such as election-related images, medical or legal advice presented as real, etc.) is prohibited.
              </li>
              <li>
                <span className="font-medium">Privacy Violations:</span> You may not upload or generate content that violates another person's privacy or rights of publicity. This means do not submit personal data about others (e.g., photos of people who have not consented) or create images of real individuals without their permission in contexts that could be deemed sensitive or invasive. Non-consensual sexual images or "revenge porn," as well as non-consensual deepfakes of real people, are strictly prohibited.
              </li>
              <li>
                <span className="font-medium">Security Breaches:</span> You must not use the Service to engage in any activity that undermines the security or integrity of Soreal's systems. This includes attempting to probe, scan, or test the vulnerability of the Service or any related system or network, breaching authentication or security measures, launching denial-of-service attacks, or intentionally introducing malware or harmful code.
              </li>
              <li>
                <span className="font-medium">Automated Abuse:</span> Do not deploy bots, scripts, or automated tools to access the Service in an unauthorized manner. The only permissible automated access is via the official Soreal API using a valid key and within the allowed usage limits. Scraping the Site, spamming requests, or any form of automation intended to extract data or circumvent usage limits without permission is prohibited.
              </li>
              <li>
                <span className="font-medium">Model Extraction or Reverse Engineering:</span> You may not attempt to extract the underlying models, datasets, or source code of Soreal through any means. This prohibition includes attempting to reverse-engineer the AI model outputs to recreate the model, using output text or images to probe the model architecture beyond normal use, or disassembling or decompiling any software provided as part of the Service.
              </li>
            </ul>
            <p className="text-gray-700 font-light leading-relaxed mt-4">
              <span className="font-medium">Enforcement:</span> Violations of this Acceptable Use Policy may result in suspension or termination of your account, removal of offending content, and potential legal consequences. Soreal reserves the right to investigate any misuse of the Service. If you are found to be using Soreal for illegal purposes or any prohibited activities (such as the forgery or fraud examples listed above), we may immediately terminate your account and block your IP address to prevent further abuse. Serious violations may also be reported to law enforcement or other appropriate authorities. You are responsible for any consequences of breaching these rules, including legal liabilities and damages to Soreal or others.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              10. Public Gallery & Community Assets
            </h2>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Default Inclusion (Free Tier).</span> If you use the Free Tier, by default your generated Assets may be showcased in a public gallery or community feed accessible to other users or visitors. These Free Tier Assets might be made available under a Creative Commons Attribution-NonCommercial-NoDerivatives (CC BY-NC-ND) license or a similar license, which allows others to view and share the content with attribution, but not to use it commercially or create derivative works. If applicable law prohibits such a default licensing (in certain jurisdictions, for example), this default inclusion may not apply to you, but by using the Free Tier you still grant Soreal the rights outlined in Section 6.1 and 6.3 for gallery display and model training.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Paid Tier Opt-In.</span> If you are a Paid Tier user, nothing you create will be displayed in the public gallery unless you affirmatively opt-in to share it. We value the privacy and ownership rights of our Paid users. Should you choose to opt-in for certain Assets, you can select those for public listing (e.g., via a toggle or setting in your account or when you generate the image). Opting in will typically apply a CC BY-NC-ND license to those Assets for community sharing purposes (unless you specify a different sharing license and we agree to it). You retain full ownership of your Assets (as per Section 6.2) even if they are displayed publicly.
            </p>
            <p className="text-gray-700 font-light leading-relaxed">
              <span className="font-medium">Takedown Requests.</span> Whether you are a Free or Paid user, if any of your Assets are publicly displayed (with your consent or by default) and you later wish to remove them from the gallery, you may submit a takedown request. To request removal of an Asset you own from public display, please email us at legal@soreal.app with the details of the image in question. We will endeavor to remove the specified Asset from our public gallery within a commercially reasonable timeframe. Note that third parties who have already accessed or shared the image (consistent with the applicable license) may still retain copies, and Soreal is not responsible for such downstream copies. However, Soreal will cease any further public distribution of the Asset upon your request (except as needed for archival or legal record-keeping purposes).
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              11. Suspension, Termination & Survival
            </h2>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">User Cancellation.</span> You have the right to cancel your Soreal account or subscription at any time. You can initiate cancellation through your account settings or by contacting customer support. If you cancel a Paid Tier subscription, you will retain access to Paid features until the end of the current billing period for which you have paid, after which your account will revert to the Free Tier (or be closed, if you choose). No prorated refunds will be provided for the remaining period except as required by law or explicitly provided in a promotion or policy. Your cancellation will not affect any rights you have in Assets already created, but it will terminate your ability to generate new Assets under the Paid Tier once the period ends.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Our Termination Rights.</span> We reserve the right to suspend or terminate your access to the Service (including any active subscription and your account) at our discretion if we believe that: (i) you have violated these Terms (including the Acceptable Use Policy or any other incorporated policies), or (ii) your use of the Service creates risk or legal exposure for Soreal or for other users. In serious cases of abuse or unlawful conduct, termination may be immediate and without prior notice. We may also implement technical measures to block your access to the Service (for example, blocking specific accounts or IP addresses) in order to enforce these Terms and prevent further violations.
            </p>
            <p className="text-gray-700 font-light leading-relaxed">
              <span className="font-medium">Effect of Termination.</span> Upon any termination of your account, whether initiated by you or by us, all licenses and rights granted to you under these Terms will immediately cease (except that you will retain ownership of Assets as described below). If you were on the Paid Tier, you will keep all ownership rights to any Assets already properly generated and paid for prior to termination (Sections 6.2 and 10 continue to apply). However, you must immediately stop using the Service, and you will no longer have access to your account or any Credits or benefits associated with it. We strongly recommend that you back up any Assets or data you need before canceling or if we notify you of an upcoming termination, as after the account is closed we may delete your stored Assets and User Content in accordance with our data retention policies. Sections of these Terms that by their nature should survive termination (including but not limited to provisions on Disclaimers, Limitation of Liability, Indemnification, Governing Law, and Dispute Resolution) will remain in effect even after your access to the Service ends.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              12. Disclaimers
            </h2>
            <p className="text-gray-700 font-light leading-relaxed uppercase">
              THE SERVICE (INCLUDING THE SITE, API, SOFTWARE, AND ALL FEATURES), ALL ASSETS, AND ANY OTHER PRODUCTS OR MATERIALS PROVIDED BY SOREAL ARE PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTY OF ANY KIND. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SOREAL DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE, INCLUDING ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ANY WARRANTIES THAT MAY ARISE FROM COURSE OF DEALING OR USAGE OF TRADE.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mt-4">
              Without limiting the generality of the foregoing, we do not guarantee that the Service or Assets will meet your requirements or expectations, or that the Service will be uninterrupted, secure, or error-free. We make no warranty that results obtained from the use of the Service will be accurate or reliable, or that any defects in the Service will be corrected. No advice or information, whether oral or written, obtained from Soreal or through the Service, shall create any warranty not expressly stated in these Terms.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              13. Limitation of Liability
            </h2>
            <p className="text-gray-700 font-light leading-relaxed uppercase">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL SOREAL AI, LLC, NOR ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR AFFILIATES, BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR ACCESS TO OR USE OF (OR INABILITY TO USE) THE SERVICE OR ANY ASSETS. THIS LIMITATION OF LIABILITY APPLIES TO ALL TYPES OF CLAIMS, WHETHER BASED IN CONTRACT, TORT, STRICT LIABILITY, VIOLATION OF LAW, OR OTHERWISE, AND WHETHER OR NOT SOREAL HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mt-4">
              To the extent that the foregoing limitation of liability is not enforceable under applicable law, you agree that Soreal's total cumulative liability for all claims in connection with the Service and these Terms shall not exceed the greater of: (a) US $50.00, or (b) the total amount you paid to Soreal for the Service in the six (6) months immediately preceding the event giving rise to the liability. The existence of multiple claims or suits under or related to these Terms will not enlarge or extend the limit of monetary damages.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              14. Indemnification
            </h2>
            <p className="text-gray-700 font-light leading-relaxed">
              You agree to defend, indemnify, and hold harmless Soreal, its parent, subsidiaries, affiliates, and their respective officers, directors, employees, and agents, from and against any and all claims, demands, lawsuits, investigations, liabilities, damages, losses, or expenses (including reasonable attorneys' fees and costs) arising out of or relating to: (i) your use of the Service or any Assets (including any activities under your account, whether by you or by any person using your account or API key); (ii) your breach or alleged breach of these Terms or any applicable law or regulation; (iii) any User Content you submit or Assets you create that infringe, misappropriate, or violate the rights of any third party (including intellectual property rights, privacy rights, or publicity rights); or (iv) your misuse of Assets or the Service, including using them in a manner not permitted by these Terms. Soreal reserves the right, at your expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you. If we do so, you agree to cooperate with our defense of such claim. You will not settle any claim subject to indemnification without Soreal's prior written consent.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              15. Governing Law & Dispute Resolution
            </h2>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Choice of Law.</span> These Terms and any dispute arising out of or related to them or the Service will be governed by and construed in accordance with the laws of the State of Delaware, USA, without regard to its conflict of law principles. However, we acknowledge that you may have rights under consumer protection laws in your home jurisdiction that cannot be waived by contract; nothing in these Terms is intended to limit your non-waivable rights, if any, under those laws.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Informal Resolution.</span> Before initiating any formal dispute resolution proceedings (such as arbitration or litigation), you agree to first contact us at legal@soreal.app and provide a written notice outlining the dispute and your desired resolution. Both you and Soreal agree to engage in good-faith discussions to attempt to resolve the issue informally. If thirty (30) days pass without a mutually satisfactory resolution, either party may then proceed to seek formal resolution as described below.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Arbitration.</span> Any dispute, claim, or controversy arising out of or relating to these Terms or the use of the Service that cannot be resolved informally shall be finally resolved by binding arbitration administered by JAMS (Judicial Arbitration and Mediation Services) in accordance with JAMS's Streamlined Arbitration Rules & Procedures. The arbitration will be conducted by a single arbitrator and, unless we agree otherwise, will take place in Orange County, California, USA (or the nearest JAMS office thereto). If you reside outside of the United States, you may elect to have the arbitration conducted remotely or in a location more convenient to you, provided JAMS can accommodate. The language of arbitration shall be English. Judgment on the arbitration award may be entered in any court having jurisdiction. Notice: By agreeing to arbitration, you are waiving your right to have most disputes heard in court by a judge or jury.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Class Action Waiver.</span> You and Soreal agree that all claims and disputes will be arbitrated or litigated only on an individual basis, and not as a class, consolidated, representative, or mass action. This means that you may not participate in any class action or representative proceeding against Soreal as a plaintiff or class member. The arbitrator may not consolidate more than one person's claims or otherwise preside over any form of a representative or class proceeding. If this class action waiver is found to be unenforceable, then the entirety of the arbitration agreement above shall be null and void, and the dispute must be brought exclusively in a state or federal court located in Orange County, California (as set forth below).
            </p>
            <p className="text-gray-700 font-light leading-relaxed">
              <span className="font-medium">Opt-Out Right.</span> You have the right to opt out of the arbitration agreement and class action waiver provisions in this Section 15 by sending a written notice of your decision to opt out to legal@soreal.app with the subject line "Arbitration Opt-Out." This opt-out notice must be emailed no later than 30 days after the first date on which you accepted these Terms (for example, the creation of your account). Your notice must include your name, your account username or email, and a clear statement that you want to opt out of the arbitration agreement. If you opt out of arbitration, you and Soreal each retain the right to resolve disputes in a court of competent jurisdiction in Orange County, California, and you agree to submit to the personal jurisdiction of that court.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              16. Modifications to Terms
            </h2>
            <p className="text-gray-700 font-light leading-relaxed">
              Soreal is an evolving service, and we may need to update or modify these Terms from time to time. If we make material changes to these Terms, we will provide you with advance notice of the changes and the date on which they become effective. We may provide such notice by sending an email to the address associated with your account, by placing a prominent notice on the Site, by in-app notification, or by other reasonable means. The notice will designate a reasonable notice period (at least fifteen (15) days, unless a longer period is required by law) before the updated Terms take effect, during which you may reject the changes by discontinuing use of the Service and (if applicable) cancelling your account.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mt-4">
              If you continue to use the Service after the new Terms become effective, that continued use will constitute your acceptance of the changes. It is your responsibility to ensure we have your current email address and to review any new Terms before they take effect. We encourage you to check the "Last updated" date at the top of these Terms whenever you use the Service to see if it has been modified since your last visit.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              17. Miscellaneous
            </h2>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Entire Agreement.</span> These Terms (together with any additional guidelines, rules, or policies that are expressly incorporated herein by reference, including the Privacy Policy) constitute the entire agreement between you and Soreal regarding the Service and supersede any prior agreements or understandings (whether written or oral) relating to the same subject matter. Any additional or different terms proposed by you (for example, in a purchase order or in any communication) are hereby rejected and will not bind Soreal unless Soreal explicitly agrees to them in a written agreement signed by an authorized representative.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Severability.</span> If any provision of these Terms is held to be invalid, illegal, or unenforceable by an arbitrator or court of competent jurisdiction, that provision shall be enforced to the maximum extent permissible, and the remaining provisions of these Terms will remain in full force and effect. Our failure to enforce any provision or exercise any right shall not constitute a waiver of future enforcement of that or any other provision.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">Assignment.</span> You may not assign or transfer any of your rights or obligations under these Terms to a third party without our prior written consent. Any purported assignment in violation of this section is null and void. Soreal may freely assign or transfer these Terms (in whole or in part) as part of a merger, acquisition, sale of assets, or by operation of law, or otherwise at our discretion.
            </p>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              <span className="font-medium">No Waiver.</span> No waiver by Soreal of any term or condition set forth in these Terms shall be deemed a further or continuing waiver of that term or any other term. Similarly, any failure of Soreal to assert a right or provision under these Terms shall not constitute a waiver of such right or provision.
            </p>
            <p className="text-gray-700 font-light leading-relaxed">
              <span className="font-medium">Force Majeure.</span> Soreal will not be liable for any delay or failure in performance of the Service or any part of these Terms to the extent such delay or failure is caused by an event or circumstance that is beyond Soreal's reasonable control. This includes, without limitation, acts of God, natural disasters, power outages, internet or telecommunications failures, cyber-attacks, labor disputes, governmental actions, or the inability to obtain necessary services or supplies. During such force majeure events, our obligations under these Terms will be suspended to the extent affected by the event.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold tracking-[-0.015em] mb-6">
              18. Contact Information
            </h2>
            <p className="text-gray-700 font-light leading-relaxed mb-4">
              If you have any questions, concerns, or feedback about these Terms or the Service, or if you need to provide any notice to Soreal under these Terms (other than for dispute resolution purposes, which are covered in Section 15), you may contact us as follows:
            </p>
            <div className="bg-gray-50 p-6 rounded-lg">
              <p className="font-medium mb-2">Soreal AI, LLC</p>
              <p className="text-gray-700 font-light">8 The Green, #18947</p>
              <p className="text-gray-700 font-light mb-4">
                Dover, DE 19901, USA
              </p>

              <p className="text-gray-700 font-light">
                Support Email:{" "}
                <a
                  href="mailto:support@soreal.app"
                  className="text-[#2fceb9] hover:underline"
                >
                  support@soreal.app
                </a>
              </p>
              <p className="text-gray-700 font-light">
                Legal/Notices Email:{" "}
                <a
                  href="mailto:legal@soreal.app"
                  className="text-[#2fceb9] hover:underline"
                >
                  legal@soreal.app
                </a>
              </p>
            </div>
            <p className="text-gray-700 font-light leading-relaxed mt-4">
              We will endeavor to respond to support inquiries in a timely manner. Please use the legal contact only for legal notices or matters and not for general support requests.
            </p>
          </section>

          <div className="border-t border-gray-200 my-8"></div>

          <p className="text-sm text-gray-500 font-light text-center">
            Last revised: 19 May 2025
          </p>
        </div>
      </div>
    </div>
  );
};

export default Page;
