// TEST
// const TOPUP_ESSENTIAL_PRICE_ID = "price_1RhRrdGGmdiYzPZ1I9ro8tdU";
// const TOPUP_CREATOR_PRICE_ID = "price_1RhRrtGGmdiYzPZ15YyKWCIG";
// const SUBSCRIPTION_STARTER_MONTHLY_PRICE_ID = "price_1RhRsEGGmdiYzPZ1mxV032Xj";
// const SUBSCRIPTION_STARTER_ANNUAL_PRICE_ID = "price_1RhRsnGGmdiYzPZ1YAyqHXz4";
// const SUBSCRIPTION_GROWTH_MONTHLY_PRICE_ID = "price_1RhRtBGGmdiYzPZ1O9oTquhi";
// const SUBSCRIPTION_GROWTH_ANNUAL_PRICE_ID = "price_1RhRtTGGmdiYzPZ1y2sKHXAw";

// PROD
const TOPUP_ESSENTIAL_PRICE_ID = "price_1RhENcGGmdiYzPZ1E2E1qtKy";
const TOPUP_CREATOR_PRICE_ID = "price_1RhENcGGmdiYzPZ1AGFYXYjY";
const SUBSCRIPTION_STARTER_MONTHLY_PRICE_ID = "price_1RhENcGGmdiYzPZ1mSEMa4JT";
const SUBSCRIPTION_STARTER_ANNUAL_PRICE_ID = "price_1RhENbGGmdiYzPZ1kr3e1pAA";
const SUBSCRIPTION_GROWTH_MONTHLY_PRICE_ID = "price_1RhENbGGmdiYzPZ1VSqgfY7f";
const SUBSCRIPTION_GROWTH_ANNUAL_PRICE_ID = "price_1RhENbGGmdiYzPZ1ZXUOYn1U";

export const topupPrices = {
  essential: TOPUP_ESSENTIAL_PRICE_ID,
  creator: TOPUP_CREATOR_PRICE_ID,
};

export const subscriptionPrices = {
  starter_monthly: SUBSCRIPTION_STARTER_MONTHLY_PRICE_ID,
  starter_annual: SUBSCRIPTION_STARTER_ANNUAL_PRICE_ID,
  growth_monthly: SUBSCRIPTION_GROWTH_MONTHLY_PRICE_ID,
  growth_annual: SUBSCRIPTION_GROWTH_ANNUAL_PRICE_ID,
};