export const sentryPaths = ["/monitoring"];

export const publicPaths = [
  "/",
  "/login",
  "/signup",
  "/forgot-password",
  "/change-password",
  "/privacy-policy",
  "/help",
  "/pricing",
  "/terms",
  "/api-docs",
  "/api-docs/quick-start",
  "/api-docs/api-reference",
  "/api-docs/api-reference/standard-image-generation",
  "/api-docs/api-reference/premium-image-generation",
  "/api-docs/api-reference/upscale-image",
  "/api-docs/api-reference/remove-background",
  "/api-docs/api-reference/get-images",
  "/confirm-email",
];

export const userPaths = [
  "/",
  "/pricing",
  "/dashboard",
  "/history",
  "/billing",
  "/settings",
  "/create",
  "/create/standard",
  "/create/premium",
  "/create/remove-background",
  "/create/upscale",
  "/api-keys",
  "/api/user",
  "/api/create-image/standard",
  "/api/create-image/premium",
  "/api/create-image/remove-background",
  "/api/create-image/upscale",
  "/api/billing/credits/verify-stripe-payment",
  "/api/enhance-prompt",
  "/change-password",
  "/help",
  "/privacy-policy",
  "/terms",
  "/api-docs",
  "/api-docs/quick-start",
  "/api-docs/api-reference",
  "/api-docs/api-reference/standard-image-generation",
  "/api-docs/api-reference/premium-image-generation",
  "/api-docs/api-reference/upscale-image",
  "/api-docs/api-reference/remove-background",
  "/api-docs/api-reference/get-images",
  "/onboarding",
  "/api/enhance-prompt",
];

export const dashboardPaths = [
  "/dashboard",
  "/history",
  "/billing",
  "/settings",
  "/create",
  "/create/standard",
  "/create/premium",
  "/create/remove-background",
  "/create/upscale",
  "/api-keys",
];

export const apiSorealPaths = [
  "/",
  "/status",
  "/create-image/standard",
  "/create-image/premium",
  "/create-image/remove-background",
  "/create-image/upscale",
  "/get-image",
];

export const authPaths = [
  "/login",
  "/signup",
  "/forgot-password",
  "/change-password",
  "/confirm-email",
];
