export const TOPUP_ESSENTIAL_PRICE_ID = "price_1RUtL6HCkRHwAvlfwnRfUzAi";
export const TOPUP_CREATOR_PRICE_ID = "price_1RVKidHCkRHwAvlfT88TZt7P";
export const SUBSCRIPTION_STARTER_MONTHLY_PRICE_ID =
  "price_1RVNWGHCkRHwAvlfRZnzmdMP";
export const SUBSCRIPTION_STARTER_ANNUAL_PRICE_ID =
  "price_1RVNYEHCkRHwAvlfbd2wFRp9";
export const SUBSCRIPTION_GROWTH_MONTHLY_PRICE_ID =
  "price_1RVNYiHCkRHwAvlfaGs4dN2c";
export const SUBSCRIPTION_GROWTH_ANNUAL_PRICE_ID =
  "price_1RVNZIHCkRHwAvlf5BBU51S3";
