export const SUPABASE_URL = "https://neupqlywpiyfnfxvuajw.supabase.co";
export const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ldXBxbHl3cGl5Zm5meHZ1YWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NDEwNjAsImV4cCI6MjA2NTAxNzA2MH0.-E9xWr09XUAfXGzeqfadcVEy2rp3MFj04vrK9qJvZjg";
