import { getImageApiUrl } from "@/constants/get-image";

export const apiEndpoints = [
  {
    name: "Get Images",
    endpoint: `${getImageApiUrl}`,
    method: "GET",
    description: "Retrieve a list of all images generated by the user.",
    parameters: [],
    response: `{
  "success": true,
  "message": "Image list fetched successfully",
  "data": [
    {
      "prompt": "beautiful sunset over the mountains",
      "generation_type": "standard",
      "public_url": "https://api.soreal.app/assets/users/1/generations/1749381948150.png",
      "created_at": "2023-06-15T10:30:45.123Z"
    },
    {
      "prompt": "futuristic cityscape at night",
      "generation_type": "advance",
      "public_url": "https://api.soreal.app/assets/users/1/generations/1749381948150.png",
      "created_at": "2023-06-16T14:22:33.456Z"
    }
  ]
}`,
    errorCodes: [
      { code: 401, message: "Unauthorized - Invalid API key" },
      { code: 429, message: "Too Many Requests - Rate limit exceeded" },
      { code: 500, message: "Internal Server Error" },
    ],
    limits: {
      rate: "10 requests per minute",
      tier: {
        basic: "500 calls/month",
        professional: "2,000 calls/month",
        enterprise: "10,000+ calls/month",
      },
      credits: 0,
    },
  },
];
